### ISSUE TITLE
new tests fails on ubuntu20.04

### ISSUE THREAD

**Issue by jkotan** [jkotan/lavue#362]
On ubuntu 20.04 in docker test we get the  following error:
```
setting up...

waiting for simple server .............................

removing '/var/lib/tango/.config/DESY/LaVue: unittests.conf'

Run: TangoAttrImageSourceTest.test_readtangofileimage() 

WARNING: Door '' cannot be found

WARNING: Door '' cannot be found

execute

Set Timer: 3000

Set Timer: 6000

Set Timer: 9000

WARNING: Door '' cannot be found

WARNING: TangoFileSource: File name not defined

WARNING: TangoFileSource: File name not defined

WARNING: DevFailed[

DevError[

    desc = BAD_INV_ORDER CORBA system exception: BAD_INV_ORDER_ORBHasShutdown

  origin = DeviceProxy::read_attribute()

  reason = API_CorbaException

severity = ERR]

DevError[

    desc = Failed to read_attribute on device test/testimageserver/00

  origin = DeviceProxy::read_attribute()

  reason = API_CommunicationFailed

severity = ERR]

]

Traceback (most recent call last):

  File "/usr/local/lib/python3.8/dist-packages/lavue-2.46.0-py3.8.egg/lavuelib/sardanaUtils.py", line 72, in decmethod

    ret = method(*args, **kwargs)

  File "/usr/local/lib/python3.8/dist-packages/lavue-2.46.0-py3.8.egg/lavuelib/liveViewer.py", line 2743, in _disconnectSource

    self.setLavueState({"connected": self.__sourcewg.isConnected()})

  File "/usr/local/lib/python3.8/dist-packages/lavue-2.46.0-py3.8.egg/lavuelib/sardanaUtils.py", line 72, in decmethod

    ret = method(*args, **kwargs)

  File "/usr/local/lib/python3.8/dist-packages/lavue-2.46.0-py3.8.egg/lavuelib/liveViewer.py", line 910, in setLavueState

    self.__imagewg.writeAttribute(

  File "/usr/local/lib/python3.8/dist-packages/lavue-2.46.0-py3.8.egg/lavuelib/imageWidget.py", line 294, in writeAttribute

    self.__tangoclient.writeAttribute(name, value)

  File "/usr/local/lib/python3.8/dist-packages/lavue-2.46.0-py3.8.egg/lavuelib/controllerClient.py", line 173, in writeAttribute

    self.__dp.write_attribute(name, value)

  File "/usr/lib/python3/dist-packages/tango/green.py", line 195, in greener

    return executor.run(fn, args, kwargs, wait=wait, timeout=timeout)

  File "/usr/lib/python3/dist-packages/tango/green.py", line 109, in run

    return fn(*args, **kwargs)

  File "/usr/lib/python3/dist-packages/tango/device_proxy.py", line 1472, in __DeviceProxy__write_attribute

    return self._write_attribute(*args, **kwargs)

TypeError: unsupported data_format.

Execute 0: _MainWindow__lavue._LiveViewer__sourcewg.isConnected

Execute 1: 

Traceback (most recent call last):

  File "/usr/lib/python3/dist-packages/qtchecker/qtChecker.py", line 384, in _executeChecks

    self.__results.append(ch.execute(self.__dialog))

  File "/usr/lib/python3/dist-packages/qtchecker/qtChecker.py", line 231, in execute

    return cmd()

  File "test/TangoAttrImageSource_test.py", line 171, in getLavueState

    self.__lavuestate = self.__lcsu.proxy.LavueState

  File "/usr/lib/python3/dist-packages/tango/device_proxy.py", line 319, in __DeviceProxy__getattr

    raise AttributeError(name)

AttributeError: LavueState

QObject::~QObject: Timers cannot be stopped from another thread

cat: testresult.txt: No such file or directory
```
It looks like a Tango/Corba problem but it is quite random, i.e. removing other tests it disappear. 
I cannot reproduce it on standard ubuntu 20.04

**Comment by jkotan** [comment]
It looks like it is interference between test timer QThread threads and Tango omnithread. To resolve the issue we need to upgrade tango to 9.3 and use in QThreads 
```python

cass JobThread(threading.Thread):
    def run(self):
        with tango.EnsureOmniThread():
            pass  # do things with subscriptions...
```
As a workaround I will split the tests.
