### ISSUE TITLE
http tests fail randomly 

### ISSUE THREAD

**Issue by jkotan** [jkotan/lavue#431]
test_readhttpimage from HttpImageSource_test.httpImageSourceTest fails randomly
```
======================================================================
FAIL: test_readhttpimage (HttpImageSource_test.httpImageSourceTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tango/test/HttpImageSource_test.py", line 260, in test_readhttpimage
    qtck4.compareResults(self, [False])
  File "/usr/lib/python3/dist-packages/qtchecker/qtChecker.py", line 440, in compareResults
    testcase.assertEqual(rs, results[i])
AssertionError: True != False

----------------------------------------------------------------------
```
which comes from 
```
2020-11-27T16:13:33.0991437Z 127.0.0.1 - - [27/Nov/2020 16:13:33] "GET /monitor/api/1.5.0/images/monitor HTTP/1.1" 200 -
2020-11-27T16:13:33.0992346Z WARNING: unpack_from requires a buffer of at least 379860 bytes
2020-11-27T16:13:33.0993864Z DEBUG: lavuelib.imageSource.HTTPSource.getData: returns ('unpack_from requires a buffer of at least 379860 bytes', '__ERROR__', '')
```

**Comment by jkotan** [comment]
or
```
2020-11-27T17:34:15.6756462Z DEBUG:lavue:lavuelib.imageSource.HTTPSource.getData: returns ('operands could not be broadcast together with shapes (0,) (2,) ', '__ERROR__', '')
```

**Comment by jkotan** [comment]
It happens when image in http mock server is not ready. To workaround the issue I add in #437 the following line
```
 'InterruptOnError=false\n'\
```
to do not stop lavue on http mock server problems
