### ISSUE TITLE
Getting images from Hidra and Http response causes crashes

### ISSUE THREAD

**Issue by jkotan** [jkotan/lavue#547]
We have been informed that using  Hidra and Http response causes crashes.

**Comment by jkotan** [comment]
```
DEBUG: lavuelib.sourceTabWidget.SourceTabWidget.isConnected: excecuted
DEBUG: lavuelib.sourceTabWidget.SourceTabWidget.isConnected: returns True
DEBUG: lavuelib.liveViewer.LiveViewer.__getNewData 1: None None , [1000, 
1000]
DEBUG: lavuelib.liveViewer.PartialData.__init__: excecuted  with (None, 
None, None, 1000, 1000, u'')
DEBUG: lavuelib.liveViewer.PartialData.__init__: returns
DEBUG: lavuelib.sourceTabWidget.SourceTabWidget.isConnected: excecuted
DEBUG: lavuelib.sourceTabWidget.SourceTabWidget.isConnected: returns True
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/lavuelib/sardanaUtils.py", line 
75, in decmethod
    ret = method(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/lavuelib/liveViewer.py", line 
3178, in _getNewData
    self.__settings.imagechannels)
  File "/usr/lib/python2.7/dist-packages/lavuelib/liveViewer.py", line 
3041, in __mergeData
    dmdata.update(json.loads(mdata))
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
TypeError: expected string or buffer
Aborted
```
