### ISSUE TITLE
lavue broken with pyqtgraph 0.13.1

### ISSUE THREAD

**Issue by beenje** [jkotan/lavue#677]
I tried running lavue with latest version of pyqtgraph (0.13.1) from conda-forge and it failed:

```
(lavue) ➜  ~ lavue --help
Traceback (most recent call last):
  File "/Users/xxxx/miniconda/envs/lavue/bin/lavue", line 37, in <module>
    import lavuelib.liveViewer
  File "/Users/xxxx/miniconda/envs/lavue/lib/python3.11/site-packages/lavuelib/liveViewer.py", line 56, in <module>
    from . import sourceTabWidget
  File "/Users/xxxx/miniconda/envs/lavue/lib/python3.11/site-packages/lavuelib/sourceTabWidget.py", line 34, in <module>
    from . import sourceWidget as swgm
  File "/Users/xxxx/miniconda/envs/lavue/lib/python3.11/site-packages/lavuelib/sourceWidget.py", line 36, in <module>
    from . import imageField
  File "/Users/xxxx/miniconda/envs/lavue/lib/python3.11/site-packages/lavuelib/imageField.py", line 38, in <module>
    class ImageField(QtGui.QDialog):
                     ^^^^^^^^^^^^^
AttributeError: module 'pyqtgraph.Qt.QtGui' has no attribute 'QDialog'
```

Looks like those imports were changed in https://github.com/pyqtgraph/pyqtgraph/commit/5d55f3facfa75f44a7490f2de55bb137cff4a029

**Comment by jkotan** [comment]
Thank you for pointing this out. I will adapt the code to the newest version of pyqtgraph

**Comment by jkotan** [comment]
Hello @beenje,

pyqtgraph 0.13 is know supported starting from lavue v2.78.0

**Comment by beenje** [comment]
Thanks!
